# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/Lab3.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/Lab3.gen/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/Lab3.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/Lab3.gen/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
