#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 11 21:08:38 PDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim dsi_tb_behav -key {Behavioral:sim_1:Functional:dsi_tb} -tclbatch dsi_tb.tcl -view /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/dsi_tb_behav.wcfg -log simulate.log"
xsim dsi_tb_behav -key {Behavioral:sim_1:Functional:dsi_tb} -tclbatch dsi_tb.tcl -view /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment3-group-7/Lab3/dsi_tb_behav.wcfg -log simulate.log

