#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Oct 24 07:23:50 PDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 57c26bcdf6924cc599faf48e76c95203 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot lab4_tb_behav xil_defaultlib.lab4_tb -log elaborate.log"
xelab -wto 57c26bcdf6924cc599faf48e76c95203 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot lab4_tb_behav xil_defaultlib.lab4_tb -log elaborate.log

