#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 24 07:23:52 PDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab4_tb_behav -key {Behavioral:sim_1:Functional:lab4_tb} -tclbatch lab4_tb.tcl -view /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment4-group-7/lab4/lab4_tb_behav.wcfg -log simulate.log"
xsim lab4_tb_behav -key {Behavioral:sim_1:Functional:lab4_tb} -tclbatch lab4_tb.tcl -view /home/josemrtnz/Documents/ECE524L/fa21-e524-lab-assignment4-group-7/lab4/lab4_tb_behav.wcfg -log simulate.log

